
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.garden.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.garden.block.StarlitWoodBlock;
import net.mcreator.garden.block.StarlitStairsBlock;
import net.mcreator.garden.block.StarlitSlabBlock;
import net.mcreator.garden.block.StarlitPressurePlateBlock;
import net.mcreator.garden.block.StarlitPlanksBlock;
import net.mcreator.garden.block.StarlitLogBlock;
import net.mcreator.garden.block.StarlitLeavesBlock;
import net.mcreator.garden.block.StarlitFenceGateBlock;
import net.mcreator.garden.block.StarlitFenceBlock;
import net.mcreator.garden.block.StarlitButtonBlock;
import net.mcreator.garden.block.SacredWoodBlock;
import net.mcreator.garden.block.SacredStairsBlock;
import net.mcreator.garden.block.SacredSlabBlock;
import net.mcreator.garden.block.SacredPressurePlateBlock;
import net.mcreator.garden.block.SacredPlanksBlock;
import net.mcreator.garden.block.SacredLogBlock;
import net.mcreator.garden.block.SacredLeavesBlock;
import net.mcreator.garden.block.SacredFenceGateBlock;
import net.mcreator.garden.block.SacredFenceBlock;
import net.mcreator.garden.block.SacredButtonBlock;
import net.mcreator.garden.block.RosewoodWoodBlock;
import net.mcreator.garden.block.RosewoodStairsBlock;
import net.mcreator.garden.block.RosewoodSlabBlock;
import net.mcreator.garden.block.RosewoodPressurePlateBlock;
import net.mcreator.garden.block.RosewoodPlanksBlock;
import net.mcreator.garden.block.RosewoodLogBlock;
import net.mcreator.garden.block.RosewoodLeavesBlock;
import net.mcreator.garden.block.RosewoodFenceGateBlock;
import net.mcreator.garden.block.RosewoodFenceBlock;
import net.mcreator.garden.block.RosewoodButtonBlock;
import net.mcreator.garden.block.LeadOreBlock;
import net.mcreator.garden.block.LeadBlockBlock;
import net.mcreator.garden.block.Blighted_BalsaWoodBlock;
import net.mcreator.garden.block.Blighted_BalsaStairsBlock;
import net.mcreator.garden.block.Blighted_BalsaSlabBlock;
import net.mcreator.garden.block.Blighted_BalsaPressurePlateBlock;
import net.mcreator.garden.block.Blighted_BalsaPlanksBlock;
import net.mcreator.garden.block.Blighted_BalsaLogBlock;
import net.mcreator.garden.block.Blighted_BalsaLeavesBlock;
import net.mcreator.garden.block.Blighted_BalsaFenceGateBlock;
import net.mcreator.garden.block.Blighted_BalsaFenceBlock;
import net.mcreator.garden.block.Blighted_BalsaButtonBlock;
import net.mcreator.garden.block.AshWoodBlock;
import net.mcreator.garden.block.AshStairsBlock;
import net.mcreator.garden.block.AshSlabBlock;
import net.mcreator.garden.block.AshPressurePlateBlock;
import net.mcreator.garden.block.AshPlanksBlock;
import net.mcreator.garden.block.AshLogBlock;
import net.mcreator.garden.block.AshLeavesBlock;
import net.mcreator.garden.block.AshFenceGateBlock;
import net.mcreator.garden.block.AshFenceBlock;
import net.mcreator.garden.block.AshButtonBlock;
import net.mcreator.garden.SgMod;

public class SgModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, SgMod.MODID);
	public static final RegistryObject<Block> ASH_LOG = REGISTRY.register("ash_log", () -> new AshLogBlock());
	public static final RegistryObject<Block> ASH_WOOD = REGISTRY.register("ash_wood", () -> new AshWoodBlock());
	public static final RegistryObject<Block> ASH_PLANKS = REGISTRY.register("ash_planks", () -> new AshPlanksBlock());
	public static final RegistryObject<Block> ASH_LEAVES = REGISTRY.register("ash_leaves", () -> new AshLeavesBlock());
	public static final RegistryObject<Block> ASH_STAIRS = REGISTRY.register("ash_stairs", () -> new AshStairsBlock());
	public static final RegistryObject<Block> ASH_SLAB = REGISTRY.register("ash_slab", () -> new AshSlabBlock());
	public static final RegistryObject<Block> ASH_FENCE = REGISTRY.register("ash_fence", () -> new AshFenceBlock());
	public static final RegistryObject<Block> ASH_FENCE_GATE = REGISTRY.register("ash_fence_gate", () -> new AshFenceGateBlock());
	public static final RegistryObject<Block> ASH_PRESSURE_PLATE = REGISTRY.register("ash_pressure_plate", () -> new AshPressurePlateBlock());
	public static final RegistryObject<Block> ASH_BUTTON = REGISTRY.register("ash_button", () -> new AshButtonBlock());
	public static final RegistryObject<Block> STARLIT_WOOD = REGISTRY.register("starlit_wood", () -> new StarlitWoodBlock());
	public static final RegistryObject<Block> STARLIT_LOG = REGISTRY.register("starlit_log", () -> new StarlitLogBlock());
	public static final RegistryObject<Block> STARLIT_PLANKS = REGISTRY.register("starlit_planks", () -> new StarlitPlanksBlock());
	public static final RegistryObject<Block> STARLIT_LEAVES = REGISTRY.register("starlit_leaves", () -> new StarlitLeavesBlock());
	public static final RegistryObject<Block> STARLIT_STAIRS = REGISTRY.register("starlit_stairs", () -> new StarlitStairsBlock());
	public static final RegistryObject<Block> STARLIT_SLAB = REGISTRY.register("starlit_slab", () -> new StarlitSlabBlock());
	public static final RegistryObject<Block> STARLIT_FENCE = REGISTRY.register("starlit_fence", () -> new StarlitFenceBlock());
	public static final RegistryObject<Block> STARLIT_FENCE_GATE = REGISTRY.register("starlit_fence_gate", () -> new StarlitFenceGateBlock());
	public static final RegistryObject<Block> STARLIT_PRESSURE_PLATE = REGISTRY.register("starlit_pressure_plate", () -> new StarlitPressurePlateBlock());
	public static final RegistryObject<Block> STARLIT_BUTTON = REGISTRY.register("starlit_button", () -> new StarlitButtonBlock());
	public static final RegistryObject<Block> SACRED_WOOD = REGISTRY.register("sacred_wood", () -> new SacredWoodBlock());
	public static final RegistryObject<Block> SACRED_LOG = REGISTRY.register("sacred_log", () -> new SacredLogBlock());
	public static final RegistryObject<Block> SACRED_PLANKS = REGISTRY.register("sacred_planks", () -> new SacredPlanksBlock());
	public static final RegistryObject<Block> SACRED_LEAVES = REGISTRY.register("sacred_leaves", () -> new SacredLeavesBlock());
	public static final RegistryObject<Block> SACRED_STAIRS = REGISTRY.register("sacred_stairs", () -> new SacredStairsBlock());
	public static final RegistryObject<Block> SACRED_SLAB = REGISTRY.register("sacred_slab", () -> new SacredSlabBlock());
	public static final RegistryObject<Block> SACRED_FENCE = REGISTRY.register("sacred_fence", () -> new SacredFenceBlock());
	public static final RegistryObject<Block> SACRED_FENCE_GATE = REGISTRY.register("sacred_fence_gate", () -> new SacredFenceGateBlock());
	public static final RegistryObject<Block> SACRED_PRESSURE_PLATE = REGISTRY.register("sacred_pressure_plate", () -> new SacredPressurePlateBlock());
	public static final RegistryObject<Block> SACRED_BUTTON = REGISTRY.register("sacred_button", () -> new SacredButtonBlock());
	public static final RegistryObject<Block> ROSEWOOD_WOOD = REGISTRY.register("rosewood_wood", () -> new RosewoodWoodBlock());
	public static final RegistryObject<Block> ROSEWOOD_LOG = REGISTRY.register("rosewood_log", () -> new RosewoodLogBlock());
	public static final RegistryObject<Block> ROSEWOOD_PLANKS = REGISTRY.register("rosewood_planks", () -> new RosewoodPlanksBlock());
	public static final RegistryObject<Block> ROSEWOOD_LEAVES = REGISTRY.register("rosewood_leaves", () -> new RosewoodLeavesBlock());
	public static final RegistryObject<Block> ROSEWOOD_STAIRS = REGISTRY.register("rosewood_stairs", () -> new RosewoodStairsBlock());
	public static final RegistryObject<Block> ROSEWOOD_SLAB = REGISTRY.register("rosewood_slab", () -> new RosewoodSlabBlock());
	public static final RegistryObject<Block> ROSEWOOD_FENCE = REGISTRY.register("rosewood_fence", () -> new RosewoodFenceBlock());
	public static final RegistryObject<Block> ROSEWOOD_FENCE_GATE = REGISTRY.register("rosewood_fence_gate", () -> new RosewoodFenceGateBlock());
	public static final RegistryObject<Block> ROSEWOOD_PRESSURE_PLATE = REGISTRY.register("rosewood_pressure_plate", () -> new RosewoodPressurePlateBlock());
	public static final RegistryObject<Block> ROSEWOOD_BUTTON = REGISTRY.register("rosewood_button", () -> new RosewoodButtonBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_WOOD = REGISTRY.register("blighted_balsa_wood", () -> new Blighted_BalsaWoodBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_LOG = REGISTRY.register("blighted_balsa_log", () -> new Blighted_BalsaLogBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_PLANKS = REGISTRY.register("blighted_balsa_planks", () -> new Blighted_BalsaPlanksBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_LEAVES = REGISTRY.register("blighted_balsa_leaves", () -> new Blighted_BalsaLeavesBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_STAIRS = REGISTRY.register("blighted_balsa_stairs", () -> new Blighted_BalsaStairsBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_SLAB = REGISTRY.register("blighted_balsa_slab", () -> new Blighted_BalsaSlabBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_FENCE = REGISTRY.register("blighted_balsa_fence", () -> new Blighted_BalsaFenceBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_FENCE_GATE = REGISTRY.register("blighted_balsa_fence_gate", () -> new Blighted_BalsaFenceGateBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_PRESSURE_PLATE = REGISTRY.register("blighted_balsa_pressure_plate", () -> new Blighted_BalsaPressurePlateBlock());
	public static final RegistryObject<Block> BLIGHTED_BALSA_BUTTON = REGISTRY.register("blighted_balsa_button", () -> new Blighted_BalsaButtonBlock());
	public static final RegistryObject<Block> LEAD_ORE = REGISTRY.register("lead_ore", () -> new LeadOreBlock());
	public static final RegistryObject<Block> LEAD_BLOCK = REGISTRY.register("lead_block", () -> new LeadBlockBlock());
}
